name: Azure Container Registry CI/CD

on:
  push:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build the project
      run: dotnet build --no-restore
    - name: Debug - Print JWT Signing key
      run: echo "The value of JWT signing key is '${{ secrets.JWT_SIGNINGKEY }}"'
    - name: Run tests
      env: 
        JWT__SIGNINGKEY: ${{ secrets.JWT_SIGNINGKEY }}
      run: dotnet test --no-build --verbosity normal

  deploy:  
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Login to Azure Container Registry
      run: |
        az acr login --name azurestudentsregistry --username ${{ secrets.AZURE_ACR_USERNAME }} --password ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t azurestudentsregistry.azurecr.io/azurestudents/azurestudentsapi:latest -f ./AzureStudents.Api/Dockerfile .

    - name: Push Docker Image
      run: |
        docker push azurestudentsregistry.azurecr.io/azurestudents/azurestudentsapi:latest      
